### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by jab** [ianozsvald/ipython_memory_usage#4]
Thanks for publishing this useful package! Any interest in uploading it to PyPI so it's easier for users to discover and install?

**Comment by ianozsvald** [comment]
Hey there. So - I probably should and I'll mull this. If a second person did a +1 here I'd give it more consideration. I'm a bit cautious as if I do this, it is yet-another-thing to support on my already-and-always-thin spare time!

**Comment by brainwane** [comment]
I am leaving a :+1: here but I'm also offering some unsolicited advice:

* consider leaving an http://unmaintained.tech/ badge on your README
* https://packaging.python.org/tutorials/distributing-packages/ is pretty thorough, if you haven't looked at the new PyPI, twine, and similar stuff for a bit

**Comment by ianozsvald** [comment]
@brainwane hey there, well, that was quick, thanks! Can I confirm that both yourself and @jab are using this? I confess that I haven't needed it for a couple of years, but if "it works" then I'm open to doing the pypi piece (I've done it before for a different project). Could you both confirm please which version of Python (3.6? earlier?) you're using and which numpy version?
I haven't tested this since the better numpy temporary-reuse code was added, I'd figured that this library was less useful as a result: https://docs.scipy.org/doc/numpy-1.13.0/release.html

**Comment by jab** [comment]
Thanks for being willing to do this!
I’m confused by the assumption I’m using numpy – I’m not. Here is an example of how I used this recently: https://github.com/jab/bidict/pull/56#issuecomment-368203591
I used it to measure the effect of a memory usage improvement in my bidict library on both Python 2.7 and Python 3.6. (I was only trying to do a quick benchmark so using the latest Python 2 and 3 versions was enough.)

**Comment by ianozsvald** [comment]
Hah! So that reminds me of Samuel L Jackson and what happens when you make an assumption: https://www.youtube.com/watch?v=YS3i-irQ0L0

You'll see that the README just shows the use of numpy, that was my use case and I'd just assumed that was everyone else's :-) I'm very happy to see your real life use case! For my own reference I see a couple of others now too:
* https://github.com/numpy/numpy/issues/6732
* https://github.com/pandas-dev/pandas/issues/11050
* https://github.com/liushuchun/pynote/tree/master/slots_magic
* https://github.com/jni/streaming-talk

Ok, I should update the docs using the latest Python and make a pypi entry. Cheers for the nudge!

**Comment by ianozsvald** [comment]
@jab @brainwane I'm pleased to say that thanks to the ManAHL Python Data hackathon today, with my trusty team of 6 first-timers, we've published a PyPI installer and updated the README: https://pypi.org/project/ipython-memory-usage/
